apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  # Adjust the name here accordingly
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v0.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: tech@route42.nl
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    http01: {}
